### ISSUE TITLE
[Alarm Control Panel] Keypad doesn't show for Envisalink alarm

### ISSUE THREAD

**Issue by cwhits** [ciotlosm/custom-lovelace#200] opened 2018-09-22 18:57 UTC
I use an Envisalink with HomeAssistant to expose my DSC alarm to HomeAssistant. The keypad isn't showing for me and it looks like the `show_keypad` doesn't exist any more and `hide_keypad: False` isn't forcing it either.

I'm pulling master and running Home Assistant 0.78.3.

**Comment by cwhits** [comment] 2018-09-22 19:01
Oh shoot. I'm dumb. It doesn't look like the Envisalink component supports entering a code by hand...

**Comment by cwhits** [comment] 2018-09-22 19:02
Wait, yes it does! 🤦‍♂️ 

Um, so... does this work with this card? 

According to the component, it should allow entering a code: https://www.home-assistant.io/components/envisalink/
```
Supported services:

The following services are supported by Envisalink and can be used to script or automate the alarm.

alarm_disarm: Disarms the alarm with the user code provided, or the code specified in the configuration.
```

**Comment by ciotlosm** [comment] 2018-09-27 09:06
@cwhits this card just supports adding a keypad and send code based on default parameters by alarm components. It should work if you add it, you just need to test it.

**Comment by Steve9F** [comment] 2018-10-02 18:44
I'm seeing the same behavior where the buttons don't show up. The Envisalink configuration includes the disarm code and the card show the correct states information when an alarm is pending and armed. The disarm button also works correctly and will disarm using the code provided in configuration. 

Even though the disarm code isn't needed it will be great if there were an additional option in the card to require a code and display the keypad. This will allow using different codes such as a guest code and provide a bit more security (although the Envisalink component should add the ability to require a code when disarming).

**Comment by ciotlosm** [comment] 2018-10-05 13:39
@Steve9F Now I understand your problem. Unfortunately my card won't be able to solve your problem. The way you want your setup to work is:

You want the card to show the keypad
You want the code to be sent to home assistant
You want home assistant to forward the command + this code to Envisalink

The problem is with the Envisalink that needs to support this "pass thru" for the code. I don't have an Envisalink to test your component, but I guess this is something for that backend component to work out. 

I will close this issue as it's not related to this card specifically, but I understand your pain. You can point to this issue if you decide to open an Enhancement request for the Envisalink in Home Assistant.

**Closed by ciotlosm** 2018-10-05 13:39 UTC
Labels: help wanted
