### ISSUE TITLE
Cannot get entity attributes card to work :(

### ISSUE THREAD

**Issue by tatunts** [ciotlosm/custom-lovelace#51] opened 2018-07-12 19:29 UTC
Hello everyone! I've been trying for a couple of days without success get this useful custom card to work.

I want to create a cart just for the vacuum, but I get this:

![image](https://user-images.githubusercontent.com/25224882/42654865-807f5e64-85f0-11e8-9914-b80fa303ccae.png)

This is my code:

```yaml
- type: entities
  title: Aspirador
  show_header_toggle: no
  entities:
    - switch.aspirador
    - sensor.xiaomi_status
    - sensor.xiaomi_battery_level
    - input_select.estados_de_succao
    - input_select.zonas_de_aspiracao
    - type: custom:entity-attributes-card
      entity: vacuum.aspirador
      attributes:
        - key: vacuum.aspirador.do_not_disturb
          name: "Não perturbe"
        - key: vacuum.aspirador.cleaning_time
          name: "Tempo limpando"
        - key: vacuum.aspirador.cleaned_area
          name: "Área limpa"
        - key: vacuum.aspirador.main_brush_left
          name: "Escova principal"
        - key: vacuum.aspirador.side_brush_left
          name: "Escova lateral"
        - key: vacuum.aspirador.filter_left
          name: "Filtro"
```

Here is the list of all attributes:

```
status: Charging
battery_level: 100
battery_icon: mdi:battery-charging-100
fan_speed: Balanced
fan_speed_list: Quiet,Balanced,Turbo,Max
do_not_disturb: off
do_not_disturb_start: 22:00:00
do_not_disturb_end: 08:00:00
cleaning_time: 2
cleaned_area: 2
cleaning_count: 39
total_cleaned_area: 222
total_cleaning_time: 302
main_brush_left: 294
side_brush_left: 194
filter_left: 144
friendly_name: Aspirador
supported_features: 2047
```

Did I miss something here?

Thanks a lot!

**Comment by ciotlosm** [comment] 2018-07-12 19:40
@tatunts did you do steps in the [FAQ](https://github.com/ciotlosm/custom-lovelace/#faq)? 
Do you have any Javascript errors in the Console?

Are you sure you cleared your cache? Usually it's easier to just add at the end of your resources ?v=1 or a higher number if you already had 1 to force browsers to ignore the cache.

**Comment by tatunts** [comment] 2018-07-13 12:45
Hello @ciotlosm! Thanks for your reply

I have these errors:

```
blob:http://192.168.4.100:8123/43888cc0-a47e-402c-2c67-1c58121d9c8e:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
/C:/Users/tatunts/AppData/Local/Google/Chrome/User%20Data/Default/Extensions/fnmpfimijcopbiaiobinamadmnmhckmp/5.7.8_0/js/content/views/report.js:20 Uncaught ReferenceError: define is not defined
    at /C:/Users/tatunts/AppData/Local/Google/Chrome/User%20Data/Default/Extensions/fnmpfimijcopbiaiobinamadmnmhckmp/5.7.8_0/js/content/views/report.js:20
casa:1 Uncaught (in promise) DOMException: Only secure origins are allowed (see: https://goo.gl/Y0ZkNV).
```

I've also cleared cache and change the resource path for the js...

Thanks!

**Comment by ciotlosm** [comment] 2018-07-13 16:29
@tatunts happy to close this issue?

**Comment by tatunts** [comment] 2018-07-13 17:32
Sorry @ciotlosm, I was not able to fix it, I just replied with the information you had asked. The card still does not show any attributes. Any ideas? Thanks a lot for your time to help me!

**Comment by ciotlosm** [comment] 2018-07-13 18:52
@tatunts The js errors show more problems with the platform, but not specific to this custom card. If you want you can join Discord channel (https://discord.gg/c5DvZ4e) and ping people on #lovelace channel.

**Comment by tatunts** [comment] 2018-07-13 20:02
@ciotlosm ok, got it! So there is nothing wrong with my code, right? Thanks again!

**Comment by ciotlosm** [comment] 2018-07-13 20:31
Doesn't seem like it, but as I mentioned, I'm mostly on discord and there are also others that could help out easier than this slow going on github issue comments :)

**Comment by ciotlosm** [comment] 2018-07-13 21:52
It seems the problem is with Lovelace and people running Home Assistant on HTTP. Lovelace uses a service worker and Chrome specifically blocks some things for the service worker if it's not using TLS (HTTPS). 

If you want to run HTTP you must call your home assistant either from localhost, or from something with .local or use HTTPS

**Comment by tatunts** [comment] 2018-07-14 12:45
Thanks @ciotlosm! I will enable HTTPS ASAP, had many problem with HomeBridge but now using HomeKit native and am about to migrate do HassOS. Thanks for your time! It helped a great deal sir. Cheers!

**Closed** 2018-07-14 12:45 UTC
Labels: help wanted
